plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://guessing-machine.github.io
baseurl: /grokc

title: Guessing Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Guessing-Machine
  instructions_file: complete_guessing.txt
  token: grok.txt
  apiUrl: https://api.x.ai/v1/completions

app:
  worker_name: grokcapi.js

lm:
  model: grok-3-mini
  max_tokens: 8192
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95

github_settings:
  owner: guessing-machine
  repo: guessing_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
